name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [custom_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Log event payload to a file
      run: echo '${{ toJson(github.event) }}' > event_payload.json

    - name: Read event payload into environment variable
      id: read_payload
      run: echo "EVENT_PAYLOAD=$(cat event_payload.json | jq -c .)" >> $GITHUB_ENV
      
 #   - name: Trigger workflow for ratting repository
 #     env:
 #        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
 #        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
 #     run: |
 #      curl -X POST -H "Accept: application/vnd.github.v3+json" \
 #      -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
 #      https://api.github.com/repos/ravi-dhyani8881/ratting/dispatches \
 #      -d "{\"event_type\":\"trigger-ratting-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

    - name: Trigger workflow for chef-solr-automation repository
      env:
        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
        https://api.github.com/repos/ravi-dhyani8881/Chef-automation-solr/dispatches \
        -d "{\"event_type\":\"trigger-solr-automation-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

    - name: Trigger workflow for chef-rest-automation repository
      env:
        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
        https://api.github.com/repos/ravi-dhyani8881/Chef-automation-rest/dispatches \
        -d "{\"event_type\":\"trigger-rest-automation-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

    - name: Trigger workflow for chef-graphql-automation repository
      env:
        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
        https://api.github.com/repos/ravi-dhyani8881/Chef-automation-graphiql/dispatches \
        -d "{\"event_type\":\"trigger-graphql-automation-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

    - name: Trigger workflow for chef-graphql-voyager repository
      env:
        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
        https://api.github.com/repos/ravi-dhyani8881/Chef-automation-voyager/dispatches \
        -d "{\"event_type\":\"trigger-voyager-automation-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

    - name: Extract organization ID
      run: |
          organizationID=$(jq -r '.client_payload.data.organizationID' event_payload.json)
          graphID=$(jq -r '.client_payload.data.graphID' event_payload.json)
          version=$(jq -r '.client_payload.data.version' event_payload.json)
          echo "Organization ID is: $organizationID"
          echo "graph ID  is: $graphID"
          echo "version is: $version"

#    - name: Trigger compile Solr code to run
#      env:
#        OTHER_REPO_GITHUB_TOKEN: ${{ secrets.OTHER_REPO_GITHUB_TOKEN }}
#        EVENT_PAYLOAD: ${{ env.EVENT_PAYLOAD }}
#      run: |
#        curl -X POST -H "Accept: application/vnd.github.v3+json" \
#        -H "Authorization: token $OTHER_REPO_GITHUB_TOKEN" \
#        https://api.github.com/repos/ravi-dhyani8881/solr-docker/dispatches \
#        -d "{\"event_type\":\"trigger-solr-docker-code-compile-workflow\", \"client_payload\": $EVENT_PAYLOAD}"

