name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [custom_event]  # Ensure this matches your EVENT_TYPE in the script

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Log event payload
      run: echo '${{ toJson(github.event) }}' | jq
